"""Canonical tool inventory metadata (names + descriptions)."""
from __future__ import annotations

from typing import List

from . import definitions as D
from .spec import ToolSpec

# Keep in sync with register_all() — golden set for CI / design invariants
ALL_TOOL_NAMES = frozenset(
    {
        "get_nodes",
        "get_node_status",
        "list_node_networks",
        "get_node_subscription",
        "list_node_certificates",
        "get_node_report",
        "list_node_services",
        "get_node_time",
        "wake_node",
        "get_cluster_status",
        "get_next_vmid",
        "get_task_status",
        "list_tasks",
        "wait_for_task",
        "get_version",
        "get_mcp_capabilities",
        "get_cluster_resources",
        "get_cluster_log",
        "get_cluster_options",
        "get_vms",
        "create_vm",
        "get_vm_config",
        "update_vm_config",
        "execute_vm_command",
        "start_vm",
        "stop_vm",
        "shutdown_vm",
        "reset_vm",
        "reboot_vm",
        "suspend_vm",
        "resume_vm",
        "delete_vm",
        "clone_vm",
        "resize_vm_disk",
        "convert_vm_to_template",
        "get_vm_status",
        "get_vm_rrd_data",
        "create_vnc_ticket_vm",
        "create_spice_ticket_vm",
        "create_termproxy_ticket_vm",
        "get_containers",
        "create_lxc",
        "get_lxc_config",
        "update_lxc_config",
        "start_lxc",
        "stop_lxc",
        "shutdown_lxc",
        "reboot_lxc",
        "suspend_lxc",
        "resume_lxc",
        "delete_lxc",
        "update_lxc_features",
        "clone_lxc",
        "resize_lxc_disk",
        "convert_lxc_to_template",
        "execute_lxc_command",
        "set_lxc_password",
        "set_lxc_ssh_keys",
        "prepare_lxc_for_docker",
        "push_to_lxc",
        "pull_from_lxc",
        "get_lxc_status",
        "get_lxc_network",
        "get_lxc_rrd_data",
        "create_vnc_ticket_lxc",
        "create_spice_ticket_lxc",
        "create_termproxy_ticket_lxc",
        "start_guest",
        "stop_guest",
        "shutdown_guest",
        "reboot_guest",
        "delete_guest",
        "get_guest_status",
        "get_guest_pending",
        "move_guest_disk",
        "list_snapshots",
        "create_snapshot",
        "delete_snapshot",
        "rollback_snapshot",
        "create_backup",
        "list_backups",
        "restore_backup",
        "delete_backup",
        "list_backup_jobs",
        "create_backup_job",
        "delete_backup_job",
        "get_storage",
        "get_storage_content",
        "list_os_templates",
        "list_isos",
        "delete_storage_content",
        "download_url_to_storage",
        "create_storage",
        "update_storage",
        "delete_storage",
        "migrate_guest",
        "get_ha_status",
        "list_ha_groups",
        "create_ha_group",
        "delete_ha_group",
        "list_ha_resources",
        "create_ha_resource",
        "update_ha_resource",
        "delete_ha_resource",
        "get_cluster_firewall_options",
        "set_cluster_firewall_options",
        "list_cluster_firewall_rules",
        "create_cluster_firewall_rule",
        "delete_cluster_firewall_rule",
        "list_guest_firewall_rules",
        "create_guest_firewall_rule",
        "delete_guest_firewall_rule",
        "get_guest_firewall_options",
        "set_guest_firewall_options",
        "list_firewall_aliases",
        "create_firewall_alias",
        "delete_firewall_alias",
        "list_firewall_ipsets",
        "create_firewall_ipset",
        "delete_firewall_ipset",
        "list_firewall_ipset_cidrs",
        "add_firewall_ipset_cidr",
        "delete_firewall_ipset_cidr",
        "list_firewall_macros",
        "list_users",
        "get_user",
        "create_user",
        "delete_user",
        "list_groups",
        "create_group",
        "delete_group",
        "list_roles",
        "list_acl",
        "update_acl",
        "list_tokens",
        "create_token",
        "delete_token",
        "get_permissions",
        "get_token_permissions",
        "list_replication_jobs",
        "get_replication_status",
        "run_replication_job",
        "create_replication_job",
        "update_replication_job",
        "delete_replication_job",
        "list_acme_plugins",
        "list_acme_accounts",
        "get_acme_directories",
        "list_sdn_zones",
        "list_sdn_vnets",
        "list_sdn_controllers",
        "list_sdn_ipams",
        "list_sdn_dns",
        "apply_sdn",
        "list_pools",
        "get_pool",
        "create_pool",
        "update_pool",
        "delete_pool",
    }
)

_DESC_OVERRIDES = {
    "convert_vm_to_template": "CONVERT_VM_TEMPLATE_DESC",
    "convert_lxc_to_template": "CONVERT_LXC_TEMPLATE_DESC",
    "get_cluster_firewall_options": "GET_CLUSTER_FW_OPTIONS_DESC",
    "set_cluster_firewall_options": "SET_CLUSTER_FW_OPTIONS_DESC",
    "list_cluster_firewall_rules": "LIST_CLUSTER_FW_RULES_DESC",
    "create_cluster_firewall_rule": "CREATE_CLUSTER_FW_RULE_DESC",
    "delete_cluster_firewall_rule": "DELETE_CLUSTER_FW_RULE_DESC",
    "list_guest_firewall_rules": "LIST_GUEST_FW_RULES_DESC",
    "create_guest_firewall_rule": "CREATE_GUEST_FW_RULE_DESC",
    "delete_guest_firewall_rule": "DELETE_GUEST_FW_RULE_DESC",
    "get_guest_firewall_options": "GET_GUEST_FW_OPTIONS_DESC",
    "set_guest_firewall_options": "SET_GUEST_FW_OPTIONS_DESC",
}

DESTRUCTIVE_TOOLS = frozenset(
    {
        "delete_vm",
        "delete_lxc",
        "delete_guest",
        "delete_snapshot",
        "delete_backup",
        "delete_backup_job",
        "delete_storage_content",
        "delete_storage",
        "restore_backup",
        "delete_user",
        "delete_group",
        "delete_token",
        "update_acl",
        "set_cluster_firewall_options",
        "delete_cluster_firewall_rule",
        "delete_guest_firewall_rule",
        "delete_firewall_alias",
        "delete_firewall_ipset",
        "delete_firewall_ipset_cidr",
        "delete_ha_group",
        "delete_ha_resource",
        "delete_replication_job",
        "delete_pool",
        "rollback_snapshot",
        "suspend_lxc",
    }
)


def _desc_attr(tool_name: str) -> str:
    return _DESC_OVERRIDES.get(tool_name, f"{tool_name.upper()}_DESC")


def all_tool_specs() -> List[ToolSpec]:
    specs: List[ToolSpec] = []
    for name in sorted(ALL_TOOL_NAMES):
        desc = getattr(D, _desc_attr(name))
        specs.append(ToolSpec(name=name, description=desc))
    return specs
