"""Expected MCP tool inventory — keep in sync with server._setup_tools()."""

EXPECTED_TOOLS = frozenset(
    {
        # Nodes / network
        "get_nodes",
        "get_node_status",
        "list_node_networks",
        "get_node_subscription",
        "list_node_certificates",
        "get_node_report",
        "list_node_services",
        "get_node_time",
        "wake_node",
        # Cluster / tasks
        "get_cluster_status",
        "get_next_vmid",
        "get_task_status",
        "list_tasks",
        "get_version",
        "get_cluster_resources",
        "get_cluster_log",
        "get_cluster_options",
        # QEMU
        "get_vms",
        "create_vm",
        "get_vm_config",
        "update_vm_config",
        "execute_vm_command",
        "start_vm",
        "stop_vm",
        "shutdown_vm",
        "reset_vm",
        "reboot_vm",
        "suspend_vm",
        "resume_vm",
        "delete_vm",
        "clone_vm",
        "resize_vm_disk",
        "convert_vm_to_template",
        "get_vm_status",
        "get_vm_rrd_data",
        "create_vnc_ticket_vm",
        "create_spice_ticket_vm",
        "create_termproxy_ticket_vm",
        # LXC
        "get_containers",
        "create_lxc",
        "get_lxc_config",
        "update_lxc_config",
        "start_lxc",
        "stop_lxc",
        "shutdown_lxc",
        "reboot_lxc",
        "delete_lxc",
        "update_lxc_features",
        "clone_lxc",
        "resize_lxc_disk",
        "convert_lxc_to_template",
        "execute_lxc_command",
        "get_lxc_status",
        "create_vnc_ticket_lxc",
        "create_termproxy_ticket_lxc",
        # Snapshots
        "list_snapshots",
        "create_snapshot",
        "delete_snapshot",
        "rollback_snapshot",
        # Backups
        "create_backup",
        "list_backups",
        "restore_backup",
        "delete_backup",
        # Storage
        "get_storage",
        "get_storage_content",
        "delete_storage_content",
        "download_url_to_storage",
        "create_storage",
        "update_storage",
        "delete_storage",
        # Migrate
        "migrate_guest",
        # HA
        "get_ha_status",
        "list_ha_groups",
        "create_ha_group",
        "delete_ha_group",
        "list_ha_resources",
        "create_ha_resource",
        "update_ha_resource",
        "delete_ha_resource",
        # Firewall
        "get_cluster_firewall_options",
        "set_cluster_firewall_options",
        "list_cluster_firewall_rules",
        "create_cluster_firewall_rule",
        "delete_cluster_firewall_rule",
        "list_guest_firewall_rules",
        "create_guest_firewall_rule",
        "delete_guest_firewall_rule",
        "get_guest_firewall_options",
        "set_guest_firewall_options",
        "list_firewall_aliases",
        "create_firewall_alias",
        "delete_firewall_alias",
        "list_firewall_ipsets",
        "create_firewall_ipset",
        "delete_firewall_ipset",
        "list_firewall_macros",
        # Access
        "list_users",
        "get_user",
        "create_user",
        "delete_user",
        "list_groups",
        "create_group",
        "delete_group",
        "list_roles",
        "list_acl",
        "update_acl",
        "list_tokens",
        "create_token",
        "delete_token",
        "get_permissions",
        # Replication
        "list_replication_jobs",
        "get_replication_status",
        "run_replication_job",
        "create_replication_job",
        "delete_replication_job",
        # ACME
        "list_acme_plugins",
        "list_acme_accounts",
        "get_acme_directories",
        # SDN
        "list_sdn_zones",
        "list_sdn_vnets",
        "list_sdn_controllers",
        "list_sdn_ipams",
        "list_sdn_dns",
        "apply_sdn",
        # Pools
        "list_pools",
        "get_pool",
        "create_pool",
        "delete_pool",
    }
)
